version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: app
      MYSQL_PASSWORD: 098765
  
  nodejs:
    build: .
    container_name: nodejs
    command: npm start
    restart: always
    depends_on:
      - mysql